package com.alhuda.app.main.prayer_guide

data class DhikrItem(
    val id: Int,
    val titleId: String,
    val titleEn: String,
    val arabic: String,
    val latin: String,
    val translationId: String,
    val translationEn: String,
    val targetCount: Int = 1,
    val source: String = "",
)

data class PrayerGuideItem(
    val id: Int,
    val titleId: String,
    val titleEn: String,
    val subtitleId: String,
    val subtitleEn: String,
    val intentionArabic: String,
    val intentionLatin: String,
    val intentionTranslationId: String,
    val intentionTranslationEn: String,
    val stepsId: List<String>,
    val stepsEn: List<String>,
    val notesId: String = "",
    val notesEn: String = "",
)

object PrayerGuideData {

    val dhikrList: List<DhikrItem> = listOf(
        DhikrItem(
            id = 1,
            titleId = "Istighfar & Doa Keselamatan",
            titleEn = "Istighfar & Supplication for Peace",
            arabic = "أَسْتَغْفِرُ اللهَ (٣×)\n\nاللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
            latin = "Astaghfirullah (3x)\n\nAllahumma antas-salaamu wa minkas-salaam, tabaarakta yaa dzal-jalaali wal-ikraam.",
            translationId = "Aku memohon ampun kepada Allah (3x).\n\nYa Allah, Engkau adalah Dzat yang memberi keselamatan, dan dari-Mu lah keselamatan, Maha Suci Engkau wahai Dzat Pemilik Keagungan dan Kemuliaan.",
            translationEn = "I ask Allah for forgiveness (3x).\n\nO Allah, You are Peace, and from You comes peace. Blessed are You, O Owner of Majesty and Honor.",
            targetCount = 1,
            source = "HR. Muslim",
        ),
        DhikrItem(
            id = 2,
            titleId = "Tahlil & Pengagungan",
            titleEn = "Tahlil & Glorification",
            arabic = "لَا إِلٰهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ، اللَّهُمَّ لَا مَانِعَ لِمَا أَعْطَيْتَ، وَلَا مُعْطِيَ لِمَا مَنَعْتَ، وَلَا يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ",
            latin = "Laa ilaaha illallaahu wahdahu laa syariika lah, lahul-mulku wa lahul-hamdu wa huwa 'alaa kulli syai-in qadiir. Allahumma laa maani'a limaa a'thaita, wa laa mu'thiya limaa mana'ta, wa laa yanfa'u dzal-jaddi minkal-jadd.",
            translationId = "Tiada sesembahan yang berhak disembah selain Allah semata, tiada sekutu bagi-Nya. Bagi-Nya segala kerajaan dan pujian, dan Dia Maha Kuasa atas segala sesuatu. Ya Allah, tidak ada yang dapat mencegah apa yang Engkau beri, dan tidak ada yang dapat memberi apa yang Engkau cegah, dan tidak bermanfaat kekayaan bagi orang yang memilikinya dari siksaan-Mu.",
            translationEn = "None has the right to be worshipped except Allah alone, with no partner. To Him belongs all sovereignty and all praise, and He is over all things capable. O Allah, none can prevent what You give, nor give what You prevent, and the fortune of the fortunate cannot benefit against You.",
            targetCount = 1,
            source = "HR. Bukhari & Muslim",
        ),
        DhikrItem(
            id = 3,
            titleId = "Ayat Kursi",
            titleEn = "Ayat al-Kursi",
            arabic = "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ",
            latin = "Allaahu laa ilaaha illaa huwal-hayyul-qayyuum, laa ta'khudzuhuu sinatuw wa laa naum, lahuu maa fis-samaawaati wa maa fil-ardh, man dzalladzii yasyfa'u 'indahuu illaa bi-idznih, ya'lamu maa baina aidiihim wa maa khalfahum, wa laa yuhiithuuna bisyai-im min 'ilmihii illaa bimaa syaa', wasi'a kursiyyuhus-samaawaati wal-ardh, wa laa ya-uuduhuu hifzhuhumaa, wa huwal-'aliyyul-'azhiim.",
            translationId = "Allah, tidak ada tuhan selain Dia. Yang Mahahidup, yang terus-menerus mengurus (makhluk-Nya), tidak mengantuk dan tidak tidur. Milik-Nya apa yang ada di langit dan apa yang ada di bumi. Siapakah yang dapat memberi syafaat di sisi-Nya tanpa izin-Nya? Dia mengetahui apa yang ada di hadapan mereka dan apa yang ada di belakang mereka, dan mereka tidak mengetahui sesuatu apa pun dari ilmu-Nya melainkan apa yang Dia kehendaki. Kursi-Nya meliputi langit dan bumi. Dan Dia tidak merasa berat memelihara keduanya, dan Dia Mahatinggi, Mahabesar.",
            translationEn = "Allah! There is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.",
            targetCount = 1,
            source = "QS. Al-Baqarah: 255 / HR. An-Nasa'i",
        ),
        DhikrItem(
            id = 4,
            titleId = "Tasbih",
            titleEn = "Tasbih",
            arabic = "سُبْحَانَ اللهِ",
            latin = "Subhanallah",
            translationId = "Maha Suci Allah.",
            translationEn = "Glory be to Allah.",
            targetCount = 33,
            source = "HR. Muslim",
        ),
        DhikrItem(
            id = 5,
            titleId = "Tahmid",
            titleEn = "Tahmid",
            arabic = "الْحَمْدُ لِلَّهِ",
            latin = "Alhamdulillah",
            translationId = "Segala puji bagi Allah.",
            translationEn = "All praise is due to Allah.",
            targetCount = 33,
            source = "HR. Muslim",
        ),
        DhikrItem(
            id = 6,
            titleId = "Takbir",
            titleEn = "Takbir",
            arabic = "اللهُ أَكْبَرُ",
            latin = "Allahu Akbar",
            translationId = "Allah Maha Besar.",
            translationEn = "Allah is the Greatest.",
            targetCount = 33,
            source = "HR. Muslim",
        ),
        DhikrItem(
            id = 7,
            titleId = "Penyempurna Dzikir 100",
            titleEn = "Completing the Hundred",
            arabic = "لَا إِلٰهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
            latin = "Laa ilaaha illallaahu wahdahu laa syariika lah, lahul-mulku wa lahul-hamdu wa huwa 'alaa kulli syai-in qadiir.",
            translationId = "Tiada sesembahan yang berhak disembah selain Allah semata, tidak ada sekutu bagi-Nya. Milik-Nya segala kerajaan dan bagi-Nya segala pujian, dan Dia Maha Kuasa atas segala sesuatu.",
            translationEn = "None has the right to be worshipped except Allah alone, without partner. To Him belongs all kingdom and to Him is all praise, and He is over all things capable.",
            targetCount = 1,
            source = "HR. Muslim",
        ),
        DhikrItem(
            id = 8,
            titleId = "Doa Pembuka & Pujian",
            titleEn = "Opening Supplication & Salawat",
            arabic = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nالْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ حَمْدًا يُوَافِي نِعَمَهُ وَيُكَافِئُ مَزِيدَهُ، يَا رَبَّنَا لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلَالِ وَجْهِكَ وَعَظِيمِ سُلْطَانِكَ، اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَىٰ سَيِّدِنَا مُحَمَّدٍ وَعَلَىٰ آلِ سَيِّدِنَا مُحَمَّدٍ",
            latin = "Bismillahir-rahmaanir-rahiim. Alhamdulillaahi rabbil-'aalamiin hamday-yuwaafii ni'amahuu wa yukaafi-u maziidah, yaa rabbanaa lakal-hamdu kamaa yambaghii lijalaali wajhika wa 'azhiimi sulthaanik. Allahumma shalli wa sallim 'alaa sayyidinaa Muhammadin wa 'alaa aali sayyidinaa Muhammad.",
            translationId = "Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang. Segala puji bagi Allah Tuhan semesta alam, pujian yang sebanding dengan nikmat-nikmat-Nya dan menjamin tambahannya. Wahai Tuhan kami, bagi-Mu segala puji sebagaimana layak bagi keagungan wajah-Mu dan kebesaran kekuasaan-Mu. Ya Allah limpahkanlah shalawat dan salam kepada junjungan kami Nabi Muhammad beserta keluarganya.",
            translationEn = "In the name of Allah, the Entirely Merciful, the Especially Merciful. All praise is due to Allah, Lord of the worlds, praise matching His favors and securing His increase. O our Lord, to You belongs praise as befits the majesty of Your Face and greatness of Your authority. O Allah, bestow peace and blessings upon our master Muhammad and his family.",
            targetCount = 1,
        ),
        DhikrItem(
            id = 9,
            titleId = "Doa Keselamatan Agama, Dunia & Akhirat",
            titleEn = "Supplication for Well-Being",
            arabic = "اللَّهُمَّ إِنَّا نَسْأَلُكَ سَلَامَةً فِي الدِّينِ، وَعَافِيَةً فِي الْجَسَدِ، وَزِيَادَةً فِي الْعِلْمِ، وَبَرَكَةً فِي الرِّزْقِ، وَتَوْبَةً قَبْلَ الْمَوْتِ، وَرَحْمَةً عِنْدَ الْمَوْتِ، وَمَغْفِرَةً بَعْدَ الْمَوْتِ، اللَّهُمَّ هَوِّنْ عَلَيْنَا فِي سَكَرَاتِ الْمَوْتِ، وَالنَّجَاةَ مِنَ النَّارِ، وَالْعَفْوَ عِنْدَ الْحِسَابِ",
            latin = "Allahumma innaa nas-aluka salaamatan fid-diin, wa 'aafiyatan fil-jasad, wa ziyaadatan fil-'ilm, wa barakatan fir-rizq, wa taubatan qablal-maut, wa rahmatan 'indal-maut, wa maghfiratam ba'dal-maut. Allahumma hawwin 'alainaa fii sakaraatil-maut, wan-najaata minan-naar, wal-'afwa 'indal-hisaab.",
            translationId = "Ya Allah, sesungguhnya kami memohon kepada-Mu keselamatan dalam agama, kesehatan jasmani, bertambahnya ilmu, berkah rezeki, taubat sebelum mati, rahmat saat mati, dan ampunan setelah mati. Ya Allah, ringankanlah bagi kami saat sakaratul maut, selamatkanlah kami dari siksa api neraka, dan berikanlah ampunan saat hisab.",
            translationEn = "O Allah, we ask You for safety in our religion, wellness in our body, increase in knowledge, blessings in sustenance, repentance before death, mercy at death, and forgiveness after death. O Allah, ease for us the agonies of death, grant deliverance from the Fire, and forgiveness at the Reckoning.",
            targetCount = 1,
        ),
        DhikrItem(
            id = 10,
            titleId = "Doa Ampunan Orang Tua",
            titleEn = "Supplication for Parents",
            arabic = "رَبَّنَا اغْفِرْ لَنَا وَلِوَالِدَيْنَا وَارْحَمْهُمْ كَمَا رَبَّوْنَا صِغَارًا",
            latin = "Rabbanaghfir lanaa wa liwaalidaynaa warhamhum kamaa rabbayaanaa shighaaraa.",
            translationId = "Wahai Tuhan kami, ampunilah kami dan kedua orang tua kami, dan sayangilah mereka sebagaimana mereka telah mendidik kami sewaktu kecil.",
            translationEn = "Our Lord, forgive us and our parents, and have mercy upon them as they brought us up when we were small.",
            targetCount = 1,
            source = "QS. Al-Isra: 24",
        ),
        DhikrItem(
            id = 11,
            titleId = "Doa Sapu Jagad (Kebaikan Dunia Akhirat)",
            titleEn = "Comprehensive Supplication",
            arabic = "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
            latin = "Rabbanaa aatinaa fid-dunyaa hasanataw wa fil-aakhirati hasanataw wa qinaa 'adzaaban-naar.",
            translationId = "Wahai Tuhan kami, berikanlah kami kebaikan di dunia dan kebaikan di akhirat, dan lindungilah kami dari azab neraka.",
            translationEn = "Our Lord, give us in this world that which is good and in the Hereafter that which is good and protect us from the punishment of the Fire.",
            targetCount = 1,
            source = "QS. Al-Baqarah: 201",
        ),
        DhikrItem(
            id = 12,
            titleId = "Doa Keteguhan Hati & Iman",
            titleEn = "Supplication for Steadfastness",
            arabic = "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ وَعَلَىٰ طَاعَتِكَ",
            latin = "Yaa muqallibal-quluub, tsabbit qalbii 'alaa diinika wa 'alaa thaa'atik.",
            translationId = "Wahai Dzat yang membolak-balikkan hati, teguhkanlah hatiku di atas agama-Mu dan ketaatan kepada-Mu.",
            translationEn = "O Turner of the hearts, keep my heart firm upon Your religion and Your obedience.",
            targetCount = 1,
            source = "HR. Tirmidzi",
        ),
        DhikrItem(
            id = 13,
            titleId = "Doa Penutup Penerimaan Amal",
            titleEn = "Closing & Acceptance Supplication",
            arabic = "رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ، وَتُبْ عَلَيْنَا إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ\n\nوَصَلَّى اللهُ عَلَىٰ سَيِّدِنَا مُحَمَّدٍ وَعَلَىٰ آلِهِ وَصَحْبِهِ وَسَلَّمَ، وَالْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
            latin = "Rabbanaa taqabbal minnaa innaka antas-samii'ul-'aliim, wa tub 'alainaa innaka antat-tawwaabur-rahiim. Wa shallallaahu 'alaa sayyidinaa Muhammadin wa 'alaa aalihii wa shahbihii wa sallam, wal-hamdu lillaahi rabbil-'aalamiin.",
            translationId = "Wahai Tuhan kami, terimalah (amal) dari kami, sungguh Engkaulah Yang Maha Mendengar lagi Maha Mengetahui, dan terimalah taubat kami, sungguh Engkaulah Yang Maha Penerima taubat lagi Maha Penyayang. Dan semoga shalawat serta salam tercurah kepada junjungan kami Nabi Muhammad, beserta keluarga dan para sahabatnya. Dan segala puji bagi Allah Tuhan semesta alam.",
            translationEn = "Our Lord, accept this from us. Indeed You are the Hearing, the Knowing. And accept our repentance. Indeed You are the Accepting of repentance, the Merciful. May Allah send blessings and peace upon our master Muhammad, his family, and companions. All praise is due to Allah, Lord of the worlds.",
            targetCount = 1,
            source = "QS. Al-Baqarah: 127-128",
        ),
    )

    val prayerGuides: List<PrayerGuideItem> = listOf(
        PrayerGuideItem(
            id = 1,
            titleId = "Sholat Jenazah",
            titleEn = "Funeral Prayer (Janazah)",
            subtitleId = "4 Takbir tanpa ruku' dan sujud (Fardhu Kifayah)",
            subtitleEn = "4 Takbirs without ruku' or sujud (Fardh Kifayah)",
            intentionArabic = "أُصَلِّي عَلَى هَٰذَا الْمَيِّتِ أَرْبَعَ تَكْبِيرَاتٍ فَرْضَ كِفَايَةٍ مَأْمُومًا لِلَّهِ تَعَالَى",
            intentionLatin = "Ushallii 'alaa haadzal-mayyiti arba'a takbiiraatin fardha kifaayati ma'muuman lillaahi ta'aalaa.",
            intentionTranslationId = "Aku berniat sholat atas jenazah ini empat takbir fardhu kifayah sebagai makmum karena Allah Ta'ala.",
            intentionTranslationEn = "I intend to pray over this deceased four takbirs as a communal obligation following the imam for Allah the Almighty.",
            stepsId = listOf(
                "Takbir Pertama (Ihram): Mengangkat tangan seraya takbir, lalu membaca Surah Al-Fatihah.",
                "Takbir Kedua: Mengangkat tangan takbir, lalu membaca Shalawat Nabi (minimal: Allahumma shalli 'ala Muhammad).",
                "Takbir Ketiga: Mengangkat tangan takbir, lalu membaca doa untuk jenazah (Allahummaghfir lahu warhamhu wa 'aafihi wa'fu 'anhu...).",
                "Takbir Keempat: Mengangkat tangan takbir, membaca doa penutup (Allahumma laa tahrimnaa ajrahu wa laa taftinnaa ba'dahu...), lalu Salam ke kanan dan ke kiri.",
            ),
            stepsEn = listOf(
                "First Takbir: Raise hands and say Takbir, then recite Surah Al-Fatihah.",
                "Second Takbir: Say Takbir, then recite Salawat upon the Prophet (Allahumma shalli 'ala Muhammad...).",
                "Third Takbir: Say Takbir, then recite supplication for the deceased (Allahummaghfir lahu warhamhu...).",
                "Fourth Takbir: Say Takbir, recite closing supplication, then make Taslim to right and left.",
            ),
            notesId = "Jika jenazah perempuan, lafaz mayyiti diganti mayyitati, dan kata ganti lahu diganti lahaa.",
            notesEn = "If the deceased is female, change pronouns accordingly (lahu -> laha).",
        ),
        PrayerGuideItem(
            id = 2,
            titleId = "Sholat Tahajjud & Witir",
            titleEn = "Tahajjud & Witr Prayer",
            subtitleId = "Sholat sunnah malam hari setelah tidur",
            subtitleEn = "Night voluntary prayer after waking from sleep",
            intentionArabic = "أُصَلِّي سُنَّةَ التَّهَجُّدِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
            intentionLatin = "Ushallii sunnatat-tahajjudi rak'ataini lillaahi ta'aalaa.",
            intentionTranslationId = "Aku niat sholat sunnah Tahajjud dua rakaat karena Allah Ta'ala.",
            intentionTranslationEn = "I intend to pray two rak'ahs of the sunnah Tahajjud for Allah the Almighty.",
            stepsId = listOf(
                "Dilakukan minimal 2 rakaat (salam setiap 2 rakaat) setelah bangun tidur di waktu malam.",
                "Membaca Al-Fatihah dan surah pendek pada setiap rakaat.",
                "Dianjurkan memperpanjang ruku' dan sujud dengan berdoa memohon ampunan.",
                "Ditutup dengan Sholat Witir ganjil (1 atau 3 rakaat).",
            ),
            stepsEn = listOf(
                "Performed in units of two rak'ahs after waking up in the night.",
                "Recite Al-Fatihah and a surah in each rak'ah.",
                "Lengthen ruku' and sujud with humble supplication.",
                "Conclude the night prayer with odd number of Witr rak'ahs.",
            ),
        ),
        PrayerGuideItem(
            id = 3,
            titleId = "Sholat Dhuha",
            titleEn = "Dhuha Prayer",
            subtitleId = "Sholat sunnah saat matahari mulai naik",
            subtitleEn = "Forenoon voluntary prayer",
            intentionArabic = "أُصَلِّي سُنَّةَ الضُّحَى رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
            intentionLatin = "Ushallii sunnatadh-dhuhaa rak'ataini lillaahi ta'aalaa.",
            intentionTranslationId = "Aku niat sholat sunnah Dhuha dua rakaat karena Allah Ta'ala.",
            intentionTranslationEn = "I intend to pray two rak'ahs of sunnah Dhuha for Allah the Almighty.",
            stepsId = listOf(
                "Waktu pelaksanaan: Sekitar 15-20 menit setelah matahari terbit (Syuruq) hingga menjelang Dzuhur.",
                "Jumlah rakaat minimal 2 rakaat, maksimal 8 atau 12 rakaat (dikerjakan tiap 2 rakaat salam).",
                "Membaca Surah Asy-Syams pada rakaat pertama dan Adh-Dhuha pada rakaat kedua (atau surah lain).",
                "Membaca doa Dhuha setelah sholat (Allahumma innadh-dhuhaa-a dhuhaa-uk...).",
            ),
            stepsEn = listOf(
                "Time: 15-20 minutes after sunrise until shortly before Dhuhr.",
                "Performed in units of 2 rak'ahs (2, 4, 6, 8 rak'ahs).",
                "Recite Surah Ash-Shams in first rak'ah and Ad-Dhuha in second (or any surah).",
                "Recite Dhuha supplication after completion.",
            ),
        ),
        PrayerGuideItem(
            id = 4,
            titleId = "Sholat Istikharah",
            titleEn = "Istikharah Prayer",
            subtitleId = "Sholat memohon petunjuk atas pilihan",
            subtitleEn = "Prayer for seeking Allah's guidance in decisions",
            intentionArabic = "أُصَلِّي سُنَّةَ الِاسْتِخَارَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
            intentionLatin = "Ushallii sunnatal-istikhaarati rak'ataini lillaahi ta'aalaa.",
            intentionTranslationId = "Aku niat sholat sunnah Istikharah dua rakaat karena Allah Ta'ala.",
            intentionTranslationEn = "I intend to pray two rak'ahs of sunnah Istikharah for Allah the Almighty.",
            stepsId = listOf(
                "Dikerjakan sebanyak 2 rakaat kapan saja di luar waktu yang diharamkan sholat.",
                "Rakaat pertama membaca Al-Fatihah dan Al-Kafirun, rakaat kedua Al-Fatihah dan Al-Ikhlas.",
                "Setelah salam, membaca doa Istikharah yang diajarkan Rasulullah SAW seraya menyebutkan hajat pilihan yang dihadapi.",
            ),
            stepsEn = listOf(
                "Performed as two rak'ahs at any permissible prayer time.",
                "Recite Surah Al-Kafirun in 1st rak'ah and Al-Ikhlas in 2nd.",
                "After Salam, recite the prescribed Istikharah supplication stating your decision.",
            ),
        ),
        PrayerGuideItem(
            id = 5,
            titleId = "Sholat Hajat",
            titleEn = "Hajat Prayer",
            subtitleId = "Sholat sunnah memohon terkabulnya hajat",
            subtitleEn = "Prayer of need for seeking fulfillment from Allah",
            intentionArabic = "أُصَلِّي سُنَّةَ الْحَاجَةِ رَكْعَتَيْنِ لِلَّهِ تَعَالَى",
            intentionLatin = "Ushallii sunnatal-haajati rak'ataini lillaahi ta'aalaa.",
            intentionTranslationId = "Aku niat sholat sunnah Hajat dua rakaat karena Allah Ta'ala.",
            intentionTranslationEn = "I intend to pray two rak'ahs of sunnah Hajat for Allah the Almighty.",
            stepsId = listOf(
                "Dikerjakan 2 rakaat (bisa hingga 12 rakaat).",
                "Dikerjakan dengan khusyuk di waktu yang tenang (seperti sepertiga malam terakhir).",
                "Setelah salam, membaca puji-pujian kepada Allah, shalawat, dan doa hajat.",
            ),
            stepsEn = listOf(
                "Performed as two rak'ahs with sincere devotion.",
                "Best performed during peaceful times such as the last third of the night.",
                "After Salam, praise Allah, send blessings upon Prophet, and make personal du'a.",
            ),
        ),
        PrayerGuideItem(
            id = 6,
            titleId = "Panduan Sujud Sahwi, Tilawah & Syukur",
            titleEn = "Sahwi, Tilawah & Shukr Prostrations",
            subtitleId = "Tata cara sujud di luar rukun sholat biasa",
            subtitleEn = "Special prostrations rules and recitations",
            intentionArabic = "سُبْحَانَ مَنْ لَا يَنَامُ وَلَا يَسْهُو",
            intentionLatin = "Subhaana mal laa yanaamu wa laa yashuu.",
            intentionTranslationId = "Maha Suci Dzat yang tidak tidur dan tidak lupa.",
            intentionTranslationEn = "Glory be to Him Who neither sleeps nor forgets.",
            stepsId = listOf(
                "Sujud Sahwi: 2 sujud sebelum atau sesudah salam karena lupa/ragu jumlah rakaat atau meninggalkan sunnah ab'adh. Bacaan: 'Subhana man laa yanaamu wa laa yashuu'.",
                "Sujud Tilawah: 1 sujud saat membaca atau mendengar ayat Sajdah dalam Al-Qur'an. Bacaan: 'Sajada wajhiya lilladzii khalaqahu wa shawwarahu...'.",
                "Sujud Syukur: 1 sujud di luar sholat saat mendapat nikmat besar atau terhindar dari musibah, diawali takbir tanpa wudhu/menghadap kiblat (sunnah).",
            ),
            stepsEn = listOf(
                "Sujud Sahwi: 2 prostrations before/after Salam for forgetfulness or doubt in prayer.",
                "Sujud Tilawah: 1 prostration when reciting or hearing a Sajdah verse from the Quran.",
                "Sujud Shukr: 1 prostration in gratitude upon receiving good news or averting calamity.",
            ),
        ),
    )
}
